services:
  - type: web
    name: chainlit-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chainlit run chanlit_chatbot.py --host 0.0.0.0 --port $PORT --headless"
     envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: PORT
        value: 8000
